/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Ficha;
import dominio.Sistema;
import dominio.Tablero;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class PrecargaMano extends javax.swing.JFrame {

    private Sistema unS;
    private int i = 0;
    private JButton[][] botones;
    private MenuPrincipal menu;

    public PrecargaMano(Sistema unSistema, MenuPrincipal menu) {
        initComponents();
        unS = unSistema;
        this.menu = menu;
        txtColor.setText("Blanca");
        int dimension1 = unSistema.getPrecarga().getTableroFichas().length;
        int dimension2 = unSistema.getPrecarga().getTableroFichas()[0].length;
        jPanel1.setLayout(new GridLayout(dimension1, dimension2));
        botones = new JButton[dimension1][dimension2];
        int anchoTotal = this.getWidth();
        int altoTotal = this.getHeight();
        int anchoDeCasilla = anchoTotal / dimension2;
        int altoDeCasilla = altoTotal / dimension1;
        for (int j = 0; j < dimension2; j++) {
            botones[0][j] = new JButton();
            jPanel1.add(botones[0][j]);
            botones[0][j].setText(j + "");
            botones[0][j].setBackground(Color.BLUE);
            botones[0][j].setEnabled(false);
        }
        Tablero tab = unSistema.getPrecarga();
        for (int i = 1; i < dimension1; i++) {
            for (int j = 0; j < dimension2; j++) {
                botones[0][0].setText("");
                JButton jButton = new JButton();
                jButton.setBounds(anchoTotal, altoTotal, anchoDeCasilla, altoDeCasilla);
                jPanel1.add(jButton);
                botones[i][j] = jButton;
                if (tab.hayBaldosa(i, j)) {
                    botones[i][j].setBackground(Color.GRAY);
                    botones[i][j].setBorder(BorderFactory.createLineBorder(Color.GRAY));
                    botones[i][j].setEnabled(false);
                } else {
                    botones[i][j].setBackground(Color.YELLOW);
                    botones[i][j].setBorder(BorderFactory.createLineBorder(Color.GRAY));
                }
                if (j == 0) {
                    botones[0][j].setVisible(false);
                }
                if (j == 0) {
                    botones[i][0].setText((char) (i + 64) + "");
                    botones[i][0].setBackground(Color.BLUE);
                    botones[i][0].setEnabled(false);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCoordenada = new javax.swing.JTextField();
        btnMeter1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtColor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Precarga manual");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 20, 320, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese la coordenada de la ficha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 80, 400, 30);
        getContentPane().add(jTextFieldCoordenada);
        jTextFieldCoordenada.setBounds(850, 80, 130, 30);

        btnMeter1.setBackground(new java.awt.Color(0, 204, 0));
        btnMeter1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMeter1.setForeground(new java.awt.Color(255, 255, 255));
        btnMeter1.setText("Ingresar");
        btnMeter1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMeter1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeter1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMeter1);
        btnMeter1.setBounds(340, 660, 180, 60);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 900));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 130, 1130, 500);

        txtColor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtColor.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtColor);
        txtColor.setBounds(750, 80, 90, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(830, 660, 180, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrecargaManual.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-540, 0, 1930, 910);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMeter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeter1ActionPerformed
        boolean ok = this.aumento();
        if (!ok) {
            actualizarIngresos();
            jTextFieldCoordenada.setText(null);
        }
    }//GEN-LAST:event_btnMeter1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(this, "Se pondran las fichas al azar");
        unS.getPrecarga().precargaAzar();
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (i != 12) {
        JOptionPane.showMessageDialog(this, "No se terminaron de cargar las posiciones, se pondran las fichas al azar");
        unS.getPrecarga().precargaAzar();
        }
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public boolean aumento() {
        boolean ok = false;
        String color = "B";
        if (i == 0) {
            unS.getPrecarga().limpiar();
        }
        if (i < 12) {
            if (i < 5) {
                txtColor.setText("Blanca");
            } else {
                if (i == 5) {
                    txtColor.setText("Roja");
                } else {
                    color = "R";
                    txtColor.setText("Roja");
                }
            }
            String tot = jTextFieldCoordenada.getText();
            if (jTextFieldCoordenada.getText().length() < 2 || jTextFieldCoordenada.getText().length() > 3) {
                JOptionPane.showMessageDialog(this, "ERROR COORDENADA INVALIDA");
            } else {
                String fila = tot.substring(0, 1);
                String columna = tot.substring(1);
                boolean sePudo = unS.agregarFichaPrecargaMano(fila, columna, color);
                if (sePudo) {
                    i++;
                    this.actualizarIngresos();
                } else {
                    JOptionPane.showMessageDialog(this, "ERROR COORDENADA INVALIDA");
                }
            }
        }
        if (i == 12) {
            ok = true;
            btnMeter1.setEnabled(false);
        }
        return ok;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMeter1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCoordenada;
    private javax.swing.JLabel txtColor;
    // End of variables declaration//GEN-END:variables
 private void actualizarIngresos() {
        int ancho = unS.getPrecarga().getTableroFichas().length;
        int largo = unS.getPrecarga().getTableroFichas()[0].length;
        for (int m = 0; m < ancho; m++) {
            for (int j = 0; j < largo; j++) {
                if (unS.getPrecarga().hayFicha(m, j)) {
                    Ficha ficha = unS.getPrecarga().getTableroFichas()[m][j];
                    String letraFicha = unS.getPrecarga().getFicha(m, j);
                    if (letraFicha.contains("B")) {
                        ficha.setC(Color.WHITE);
                        botones[m][j].setBackground(ficha.getC());
                    } else {
                        if (letraFicha.contains("R")) {
                            ficha.setC(Color.RED);
                            botones[m][j].setBackground(ficha.getC());
                        }
                    }
                }
            }
        }
    }
}
