/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Jugador;
import javax.swing.table.DefaultTableModel;

public class Ranking extends javax.swing.JFrame {

    private DefaultTableModel tabla;
    int cont = 0;
    private MenuPrincipal menu;

    public Ranking(MenuPrincipal menu) {
        initComponents();
        this.menu = menu;
        cargarTabla();
        tblRaking.setEnabled(false);
        menu.setEnabled(false);
    }

    public void mostrarTabla(Jugador j) {
        tabla.insertRow(cont, new Object[]{});
        tabla.setValueAt(j.getNombre(), cont, 0);
        tabla.setValueAt(j.getAlias(), cont, 1);
        tabla.setValueAt(j.getPartidasGanadas(), cont, 2);
        tabla.setValueAt(j.getPartidasJugadas(), cont, 3);
        cont++;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRaking = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1025, 650));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnVolver.setBackground(new java.awt.Color(0, 204, 0));
        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(430, 560, 140, 48);

        tblRaking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRaking);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 110, 850, 420);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ranking de Jugadores");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 30, 420, 39);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRanking.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1020, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void cargarTabla() {
        String data[][] = {};
        String[] columnNames = {"Nombre", "Alias", "Partidas Ganadas", "Partidas Jugadas"};
        tabla = new DefaultTableModel(data, columnNames);
        tblRaking.setModel(tabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRaking;
    // End of variables declaration//GEN-END:variables
}
