/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodo
 */
public class RegistrarJugador extends javax.swing.JFrame {

    private Sistema miModelo;
    private MenuPrincipal menu;

    public RegistrarJugador(Sistema modelo, MenuPrincipal menu) {
        initComponents();
        miModelo = modelo;
        this.menu = menu;
        menu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnRyS = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtAlias = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Jugador");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 340, 44);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 100, 110, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 150, 70, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alias");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 200, 70, 29);

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 204));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(30, 260, 170, 60);

        btnRyS.setBackground(new java.awt.Color(0, 204, 0));
        btnRyS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRyS.setForeground(new java.awt.Color(255, 255, 255));
        btnRyS.setText("Registrar y Salir");
        btnRyS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRyS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRyS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRySActionPerformed(evt);
            }
        });
        getContentPane().add(btnRyS);
        btnRyS.setBounds(240, 260, 170, 60);

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(450, 260, 170, 60);
        getContentPane().add(txtAlias);
        txtAlias.setBounds(300, 200, 223, 20);
        getContentPane().add(txtEdad);
        txtEdad.setBounds(300, 150, 102, 20);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(300, 110, 220, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoRegistrarJugador.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 710, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (txtNombre.getText().trim().isEmpty() || txtAlias.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Faltan datos del jugador");
        } else {
            try {
                boolean seRegistro = miModelo.registrarJugador(txtNombre.getText(), Integer.parseInt(txtEdad.getText()), txtAlias.getText());
                if (seRegistro) {
                    JOptionPane.showMessageDialog(this, "Se registro el jugador");
                    txtNombre.setText(null);
                    txtEdad.setText(null);
                    txtAlias.setText(null);
                } else {
                    JOptionPane.showMessageDialog(this, "Error el alias ya esta en uso");
                    txtAlias.setText(null);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Se equivoco la edad no tiene fomato valido");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRySActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRySActionPerformed
        if (txtNombre.getText().trim().isEmpty() || txtAlias.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Faltan datos del jugador");
        } else {
            try {
                boolean seRegistro = miModelo.registrarJugador(txtNombre.getText(), Integer.parseInt(txtEdad.getText()), txtAlias.getText());
                if (seRegistro) {
                    JOptionPane.showMessageDialog(this, "Se registro el jugador");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error el alias ya esta en uso");
                    txtAlias.setText(null);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Se equivoco la edad no tiene fomato valido");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        menu.setEnabled(true);
    }//GEN-LAST:event_btnRySActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(this, "Datos del jugador perdido");
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRyS;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
