/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Jugador;
import dominio.Partida;
import dominio.Sistema;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Integer.parseInt;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodo
 */
public class ConfiguracionPartida extends javax.swing.JFrame {

    private Sistema miSistema;
    private MenuPrincipal menu;

    public Jugador getJugador1() {
        return miSistema.partidaActual().getJugador1();
    }

    public void setJugador1(Jugador jugador1) {
        miSistema.partidaActual().setJugador1(jugador1);
    }

    public Jugador getJugador2() {
        return miSistema.partidaActual().getJugador2();
    }

    public void setJugador2(Jugador jugador2) {
        miSistema.partidaActual().setJugador2(jugador2);
    }

    public Sistema getMiSistema() {
        return miSistema;
    }

    public void setMiModelo(Sistema miSistema) {
        this.miSistema = miSistema;
    }

    public ConfiguracionPartida(Sistema modelo, MenuPrincipal menu) {
        initComponents();
        this.setMinimumSize(new Dimension(400, 400));
        miSistema = modelo;
        this.menu = menu;
        menu.setEnabled(false);
        actualizarListaDeJugadores();
        actualizarListaDeJugadores2();
    }

    private void actualizarListaDeJugadores() {
        Jugador[] jugadores = new Jugador[this.getMiSistema().getListaJugadores().size()];
        for (int i = 1; i <= this.getMiSistema().getListaJugadores().size(); i++) {
            Jugador unJugador = this.getMiSistema().getListaJugadores().get(i - 1);
            jugadores[i - 1] = unJugador;
        }
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(jugadores);
        jComboBoxJugador1.setModel(comboModel);
    }

    private void actualizarListaDeJugadores2() {
        Jugador[] jugadores = new Jugador[this.getMiSistema().getListaJugadores().size()];
        for (int i = 1; i <= this.getMiSistema().getListaJugadores().size(); i++) {
            Jugador unJugador = this.getMiSistema().getListaJugadores().get(i - 1);
            jugadores[i - 1] = unJugador;
        }
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel(jugadores);
        jComboBoxJugador2.setModel(comboModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxJugador1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxJugador2 = new javax.swing.JComboBox();
        txtFichasInvertidas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnJugar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jugador 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 190, 120, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jugador 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 340, 120, 29);

        jComboBoxJugador1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxJugador1);
        jComboBoxJugador1.setBounds(680, 200, 470, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Configuracion partida");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 40, 410, 44);

        jComboBoxJugador2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxJugador2);
        jComboBoxJugador2.setBounds(680, 350, 470, 20);
        getContentPane().add(txtFichasInvertidas);
        txtFichasInvertidas.setBounds(680, 500, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad de fichas invertidas (1 a 6)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 500, 440, 29);

        btnJugar.setBackground(new java.awt.Color(0, 204, 0));
        btnJugar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("Jugar");
        btnJugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar);
        btnJugar.setBounds(200, 630, 160, 60);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(940, 630, 160, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoConfiguracionPartida.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1370, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        Jugador jugador1 = (Jugador) this.jComboBoxJugador1.getSelectedItem();
        Jugador jugador2 = (Jugador) this.jComboBoxJugador2.getSelectedItem();
        if (jugador1.equals(jugador2)) {
            JOptionPane.showMessageDialog(this, "Ya se ha seleccionado el jugador", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                if (txtFichasInvertidas.getText().trim().length() == 0) {
                    JOptionPane.showMessageDialog(this, "No ha seleccionado la cantidad de fichas invertidas", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (parseInt(txtFichasInvertidas.getText().trim()) < 1 || parseInt(txtFichasInvertidas.getText().trim()) > 6) {
                        JOptionPane.showMessageDialog(this, "Cantidad invalida de fichas invertidas", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        Partida partida = new Partida(jugador1, jugador2, parseInt(txtFichasInvertidas.getText()));
                        miSistema.agregarPartida(partida);
                        TableroJ unaVJ = new TableroJ(miSistema, menu);
                        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
                        Dimension ventana = unaVJ.getSize();
                        unaVJ.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);
                        unaVJ.setVisible(true);
                        unaVJ.setLocationRelativeTo(null);
                        unaVJ.pack();
                        this.dispose();
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Error reingrese la cantidad de fichas invertidas");
            }
        }
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnJugar;
    private javax.swing.JComboBox jComboBoxJugador1;
    private javax.swing.JComboBox jComboBoxJugador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtFichasInvertidas;
    // End of variables declaration//GEN-END:variables
}
