/*4956
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Jugador;
import dominio.Partida;
import dominio.Sistema;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodo
 */
public class MenuPrincipal extends javax.swing.JFrame implements Observer {

    private Sistema unSistema;
    public boolean sePrecargo;
    public boolean seJugoUnaPartida = false;
    private int cont = 0;

    public Sistema getMiSistema() {
        return unSistema;
    }

    public void setMiSistema(Sistema miSistema) {
        this.unSistema = miSistema;
    }

    public MenuPrincipal(Sistema sistema) {
        initComponents();
        unSistema = sistema;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarJugador = new javax.swing.JButton();
        btnJugarBaldosas = new javax.swing.JButton();
        Ranking = new javax.swing.JButton();
        btnPrecarga = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(595, 410));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnRegistrarJugador.setBackground(new java.awt.Color(255, 204, 0));
        btnRegistrarJugador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegistrarJugador.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarJugador.setText("Registrar Jugador");
        btnRegistrarJugador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrarJugador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarJugador.setPreferredSize(new java.awt.Dimension(200, 25));
        btnRegistrarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarJugador);
        btnRegistrarJugador.setBounds(40, 140, 170, 60);

        btnJugarBaldosas.setBackground(new java.awt.Color(51, 204, 0));
        btnJugarBaldosas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnJugarBaldosas.setForeground(new java.awt.Color(255, 255, 255));
        btnJugarBaldosas.setText("Jugar Baldosas");
        btnJugarBaldosas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJugarBaldosas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnJugarBaldosas.setPreferredSize(new java.awt.Dimension(200, 25));
        btnJugarBaldosas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarBaldosasActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugarBaldosas);
        btnJugarBaldosas.setBounds(210, 200, 170, 58);

        Ranking.setBackground(new java.awt.Color(255, 51, 51));
        Ranking.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Ranking.setForeground(new java.awt.Color(255, 255, 255));
        Ranking.setText("Ranking");
        Ranking.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Ranking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ranking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ranking.setPreferredSize(new java.awt.Dimension(200, 25));
        Ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RankingActionPerformed(evt);
            }
        });
        getContentPane().add(Ranking);
        Ranking.setBounds(380, 140, 170, 60);

        btnPrecarga.setBackground(new java.awt.Color(0, 0, 204));
        btnPrecarga.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrecarga.setForeground(new java.awt.Color(255, 255, 255));
        btnPrecarga.setText("Precarga");
        btnPrecarga.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrecarga.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrecarga.setPreferredSize(new java.awt.Dimension(200, 25));
        btnPrecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecargaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrecarga);
        btnPrecarga.setBounds(40, 260, 170, 60);

        btnSalir.setBackground(new java.awt.Color(102, 102, 102));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(380, 260, 170, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Baldosas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 20, 170, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Menú Principal");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 80, 270, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondeMenuPrincipal.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            unSistema.guardarSistema(unSistema);
        } catch (IOException err) {
            JOptionPane.showMessageDialog(this, "Problemas al guardar el sistema");
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnRegistrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarJugadorActionPerformed
        JOptionPane.showMessageDialog(this, "Se le recuerda que el alias es unico y no puede repetirse");
        RegistrarJugador ventana = new RegistrarJugador(unSistema, this);
        ventana.setLocationRelativeTo(null);
        ventana.pack();
        ventana.setVisible(true);
    }//GEN-LAST:event_btnRegistrarJugadorActionPerformed

    private void btnJugarBaldosasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarBaldosasActionPerformed
        if (this.getMiSistema().getListaJugadores().size() < 2) {
            JOptionPane.showMessageDialog(this, "No hay la cantidad necesaria de jugadores para iniciar ", "Error", JOptionPane.OK_CANCEL_OPTION);
        } else {
            Partida unaP = new Partida();
            if (cont == 0) {
                JOptionPane.showMessageDialog(this, "No se eligio ninguna tipo de precarga, las fichas va a estar distibuidas al azar");
                unSistema.getPrecarga().precargaAzar();
//                unSistema.agregarPartida(unaP);
//                ConfiguracionPartida sP = new ConfiguracionPartida(unSistema, this);
//                Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
//                Dimension ventana = sP.getSize();
//                sP.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);
//                sP.setVisible(true);
//                sP.setLocationRelativeTo(null);
//                sP.pack();
//            } else {
            }
            unSistema.agregarPartida(unaP);
            ConfiguracionPartida sP = new ConfiguracionPartida(unSistema, this);
            Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
            Dimension ventana = sP.getSize();
            sP.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);
            sP.setVisible(true);
            sP.setLocationRelativeTo(null);
            sP.pack();
            cont = 0;
//        }
        }
    }//GEN-LAST:event_btnJugarBaldosasActionPerformed

    private void RankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RankingActionPerformed
        if (unSistema.getListaJugadores().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se cumplen los requisitos necesarios para mostrar el ranking", "Error", JOptionPane.OK_CANCEL_OPTION);
        } else {
            Ranking cJ = new Ranking(this);
            cJ.setLocationRelativeTo(null);
            cJ.setVisible(true);
            Jugador p;
            int suma = unSistema.getListaJugadores().size();
            for (int i = 0; i < unSistema.getListaJugadores().size(); i++) {
                p = (Jugador) unSistema.getListaJugadores().get(i);
                suma = suma + p.getPartidasJugadas();
            }
            for (int j = suma; j >= 0; j--) {
                for (int i = 0; i < unSistema.getListaJugadores().size(); i++) {
                    p = (Jugador) unSistema.getListaJugadores().get(i);
                    if (p.getPartidasGanadas() == j) {
                        cJ.mostrarTabla(p);
                    }
                }
            }
        }

    }//GEN-LAST:event_RankingActionPerformed

    private void btnPrecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecargaActionPerformed
        JOptionPane.showMessageDialog(this, "Se le recuerda que esta obligado a elegir una precarga en esta opcion."
                + "\nAunque haya elegido una precarga y luego haya vuelto a ingresar en esta opcion y la quita,"
                + " se van a poner las fichas al azar");
        Precarga unReg = new Precarga(unSistema, this);
        unReg.setLocationRelativeTo(null);
        unReg.pack();
        unReg.setVisible(true);
        cont++;
    }//GEN-LAST:event_btnPrecargaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            unSistema.guardarSistema(unSistema);

        } catch (FileNotFoundException err) {
            Logger.getLogger(MenuPrincipal.class
                    .getName()).log(Level.SEVERE, null, err);
        } catch (IOException err) {
            Logger.getLogger(MenuPrincipal.class
                    .getName()).log(Level.SEVERE, null, err);
        }
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ranking;
    private javax.swing.JButton btnJugarBaldosas;
    private javax.swing.JButton btnPrecarga;
    private javax.swing.JButton btnRegistrarJugador;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
 @Override
    public void update(Observable o, Object o1) {
    }
}
