/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import dominio.Sistema;
import dominio.Tablero;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import manejoArchivos.LevantarTablero;

/**
 *
 * @author Rodo
 */
public class Precarga extends javax.swing.JFrame {

    private Sistema miSistema;
    private MenuPrincipal menu;

    public Precarga(Sistema unSistema, MenuPrincipal menu) {
        miSistema = unSistema;
        this.menu = menu;
        menu.setEnabled(false);
        initComponents();
        ArrayList<Tablero> tableros = miSistema.getListaTableros();
        int cantidad = tableros.size();
        if (cantidad != 0) {
            jComboBoxListaTableros.addItem("Seleccione un tablero");
            for (int i = 0; i < cantidad; i++) {
                jComboBoxListaTableros.addItem(tableros.get(i));
            }
        } else {
            btnprecargaTexto.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFija = new javax.swing.JButton();
        btnCargaArchivo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxListaTableros = new javax.swing.JComboBox();
        btnAzar = new javax.swing.JButton();
        btnManual = new javax.swing.JButton();
        btnprecargaTexto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 550));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnFija.setBackground(new java.awt.Color(255, 0, 0));
        btnFija.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnFija.setForeground(new java.awt.Color(255, 255, 255));
        btnFija.setText("Fija");
        btnFija.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFija.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFija.setPreferredSize(new java.awt.Dimension(35, 25));
        btnFija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFijaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFija);
        btnFija.setBounds(70, 120, 180, 60);

        btnCargaArchivo.setBackground(new java.awt.Color(51, 204, 0));
        btnCargaArchivo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCargaArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btnCargaArchivo.setText("Cargar archivo");
        btnCargaArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCargaArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargaArchivo.setPreferredSize(new java.awt.Dimension(35, 25));
        btnCargaArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargaArchivo);
        btnCargaArchivo.setBounds(420, 120, 180, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Precargas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 20, 200, 44);

        getContentPane().add(jComboBoxListaTableros);
        jComboBoxListaTableros.setBounds(640, 200, 380, 20);

        btnAzar.setBackground(new java.awt.Color(102, 102, 102));
        btnAzar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAzar.setForeground(new java.awt.Color(255, 255, 255));
        btnAzar.setText("Azar");
        btnAzar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAzar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAzar.setPreferredSize(new java.awt.Dimension(35, 25));
        btnAzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAzar);
        btnAzar.setBounds(420, 410, 180, 60);

        btnManual.setBackground(new java.awt.Color(0, 0, 204));
        btnManual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnManual.setForeground(new java.awt.Color(255, 255, 255));
        btnManual.setText("Manual");
        btnManual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManual.setPreferredSize(new java.awt.Dimension(35, 25));
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });
        getContentPane().add(btnManual);
        btnManual.setBounds(70, 410, 180, 60);

        btnprecargaTexto.setBackground(new java.awt.Color(255, 153, 51));
        btnprecargaTexto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnprecargaTexto.setForeground(new java.awt.Color(255, 255, 255));
        btnprecargaTexto.setText("Seleccionar");
        btnprecargaTexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnprecargaTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnprecargaTexto.setPreferredSize(new java.awt.Dimension(35, 25));
        btnprecargaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecargaTextoActionPerformed(evt);
            }
        });
        getContentPane().add(btnprecargaTexto);
        btnprecargaTexto.setBounds(750, 120, 180, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrecarga.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1210, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFijaActionPerformed
        miSistema.precargarFija();
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnFijaActionPerformed

    private void btnCargaArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaArchivoActionPerformed
        File archivo = precargaFichaTxt();
        if (archivo != null) {
            String path = archivo.getAbsolutePath();
            if (path != null && !path.equals("")) {
                try {
                    Tablero tablero = LevantarTablero.leerTablero(path);
                    tablero.setNombre(archivo.getName());
                    tablero.setFecha(new Date());
                    miSistema.modificarTableroPrecarga(tablero);
                    miSistema.agregarTablero(tablero.copia());
                    JOptionPane.showMessageDialog(this, "Levantado");
                    menu.setEnabled(true);
                    this.dispose();
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "No existe el archivo");
                } catch (IOException ex) {
                    Logger.getLogger(Precarga.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnCargaArchivoActionPerformed

    private void btnAzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzarActionPerformed
        miSistema.precargaAzar();
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnAzarActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        PrecargaMano pM = new PrecargaMano(miSistema, menu);
        pM.setLocationRelativeTo(null);
        this.dispose();
        pM.setVisible(true);
        pM.pack();
        this.dispose();
    }//GEN-LAST:event_btnManualActionPerformed

    private void btnprecargaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecargaTextoActionPerformed
        try {
            Tablero tablero = (Tablero) jComboBoxListaTableros.getSelectedItem();
            if (tablero != null) {
                miSistema.modificarTableroPrecarga(tablero.copia());
                menu.setEnabled(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un tablero");
            }
        } catch (ClassCastException ex) {
            JOptionPane.showMessageDialog(this, "Seleccione un tablero");
        }
    }//GEN-LAST:event_btnprecargaTextoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        JOptionPane.showMessageDialog(this, "No se eligio ninguna precarga, las fichas van a estar al azar");
        miSistema.precargaAzar();
        menu.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    public File precargaFichaTxt() {
        JFileChooser jF1 = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("txt", "TXT");
        jF1.setFileFilter(filter);
        jF1.showOpenDialog(this);
        try {
            return jF1.getSelectedFile();
        } catch (NullPointerException ex) {
            return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzar;
    private javax.swing.JButton btnCargaArchivo;
    private javax.swing.JButton btnFija;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnprecargaTexto;
    private javax.swing.JComboBox jComboBoxListaTableros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
